DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS rooms;
DROP TABLE IF EXISTS chat_history;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  username TEXT NOT NULL,
  email TEXT NOT NULL,
  email_verified BIT NOT NULL,
  role TEXT NOT NULL,
  password_hash INTEGER,
  FOREIGN KEY (id) REFERENCES rooms(id)

);

CREATE TABLE rooms (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  room_name TEXT NOT NULL,
  is_public BIT NOT NULL
);
